torchrun --nproc_per_node 8 finetuning.py \
    --model Llama7B_adapter \
    --llama_model_path ../models/LLaMA-7B \
    --data_path ../data/math_data_train.json \
    --adapter_layer 30 \
    --adapter_len 10 \
    --max_seq_len 512 \
    --batch_size 2 \
    --epochs 15 \
    --warmup_epochs 2 \
    --blr 36e-3 \
    --weight_decay 0.02 \
    --output_dir checkpoint_math/ \
    --accum_iter 4 \
    --add_bias True \
    --add_scale True \
    --train_norm True